vich_uploader:
    db_driver: orm

    mappings:
        blog_image:
            uri_prefix: /images/blog
            upload_destination: '%kernel.project_dir%/public/images/blog'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        user_avatar:
            uri_prefix: /images/user/avatar
            upload_destination: '%kernel.project_dir%/public/images/user/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        user_banner:
            uri_prefix: /images/user/banner
            upload_destination: '%kernel.project_dir%/public/images/user/banner'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
