home:
  path: /
  controller: App\Controller\HomeController::index
  methods: [GET]

guide:
  path: /guide
  controller: App\Controller\Guide\GuideController::index
  methods: [GET]

guide.markdown:
  path: /guide/markdown
  controller: App\Controller\Guide\MarkdownGuideController::index
  methods: [GET]

# Blog
blog.index:
  path: /blog
  controller: App\Controller\BlogController::index
  methods: [GET]

blog.show:
  path: /blog/{slug}-{id}
  controller: App\Controller\BlogController::show
  methods: [GET]
  requirements:
    slug:  '[a-z0-9\-]*'

blog.category:
  path: /blog/category/{slug}
  controller: App\Controller\BlogController::categoryIndex
  methods: [GET]
  requirements:
    slug: '[a-z\-]*'

blog.like:
  path: /blog/{slug}-{id}/like
  controller: App\Controller\BlogController::like
  methods: [GET]
  requirements:
    slug:  '[a-z0-9\-]*'

blog.comment:
  path: /blog/{slug}-{id}/comment/{post}
  controller: App\Controller\BlogController::comment
  methods: [POST]
  requirements:
    slug:  '[a-z0-9\-]*'

blog.reply:
  path: /blog/{slug}-{id}/reply/{comment}
  controller: App\Controller\BlogController::reply
  methods: [POST]
  requirements:
    slug:  '[a-z0-9\-]*'


# Administration
admin.home:
  path: /admin
  controller: App\Controller\Admin\DashboardController::dashboard
  methods: [GET]

# Manage Blog
admin.blog:
  path: /admin/blog
  controller: App\Controller\Admin\Blog\BlogController::index
  methods: [GET]

admin.blog.manage.post:
  path: /admin/blog/post
  controller: App\Controller\Admin\Blog\BlogController::managePost
  methods: [GET]

admin.blog.post.create:
  path: /admin/blog/post/post/create
  controller: App\Controller\Admin\Blog\BlogController::create
  methods: [GET|POST]

admin.blog.post.edit:
  path: /admin/blog/post/post/edit/{id}
  controller: App\Controller\Admin\Blog\BlogController::edit
  methods: [GET|POST]

admin.blog.post.delete:
  path: /admin/blog/post/post/{id}
  controller: App\Controller\Admin\Blog\BlogController::delete
  methods: [DELETE]

admin.blog.manage.categories:
  path: /admin/blog/post/categories
  controller: App\Controller\Admin\Blog\BlogCategoriesController::index
  methods: [GET]

admin.blog.categories.create:
  path: /admin/blog/post/categories/create
  controller: App\Controller\Admin\Blog\BlogCategoriesController::create
  methods: [GET|POST]

admin.blog.categories.edit:
  path: /admin/blog/post/categories/edit/{id}
  controller: App\Controller\Admin\Blog\BlogCategoriesController::edit
  methods: [GET|POST]

admin.blog.categories.delete:
  path: /admin/blog/post/categories/{id}
  controller: App\Controller\Admin\Blog\BlogCategoriesController::delete
  methods: [DELETE]

admin.blog.manage.comment:
  path: /admin/blog/post/comments
  controller: App\Controller\Admin\Blog\BlogCommentsController::comments
  methods: [GET|POST]

admin.blog.comment.edit:
  path: /admin/blog/post/comments/edit/{id}
  controller: App\Controller\Admin\Blog\BlogCommentsController::edit
  methods: [GET|POST]

admin.blog.comment.delete:
  path: /admin/blog/post/comments/{id}
  controller: App\Controller\Admin\Blog\BlogCommentsController::delete
  methods: [DELETE]

# Manage users
admin.users:
  path: /admin/users
  controller: App\Controller\Admin\Users\UsersController::index
  methods: [GET]

admin.user.create:
  path: /admin/users/create
  controller: App\Controller\Admin\Users\UsersController::create
  methods: [GET|POST]

admin.user.edit:
  path: /admin/users/edit/{id}
  controller: App\Controller\Admin\Users\UsersController::edit
  methods: [GET|POST]

admin.user.delete:
  path: /admin/users/{id}
  controller: App\Controller\Admin\Users\UsersController::delete
  methods: [DELETE]

# Security
login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET|POST]

logout:
  path: /logout
  methods: [GET]

register:
  path: /register
  controller: App\Controller\SecurityController::register
  methods: [GET|POST]

confirmation_account:
  path: /confirm-account/{token}-{id}
  controller: App\Controller\SecurityController::confirmAccount
  methods : [GET]

forgot_password_request:
  path: /forgot-password
  controller: App\Controller\SecurityController::forgotPasswordRequest
  methods: [GET|POST]

forgot_password_post:
  path: /forgot-password/{token}
  controller: App\Controller\SecurityController::forgotPasswordPost
  methods: [GET|POST]

change_password:
  path: /profil/{id}/security/{token}
  controller: App\Controller\Security\ChangePassword::change
  methods: [GET|POST]

github_connect:
  path: /auth/github
  controller: App\Controller\Auth\GithubAuthController::connect
  methods: [GET]

google_connect:
  path: /auth/google
  controller: App\Controller\Auth\GoogleAuthController::connect
  methods: [GET]

twitch_connect:
  path: /auth/twitch
  controller: App\Controller\Auth\TwitchAuthController::connect
  methods: [GET]

# Profil

profil.index:
  path: /profil/{id}
  controller: App\Controller\Profil\ProfilController::profil
  methods: [GET]

#profil.privacy:
#  path: /profil/{id}/privacy

profil.details:
  path: /profil/{id}/details
  controller: App\Controller\Profil\ProfilController::details
  methods: [GET|POST]

profil.security:
  path: /profil/{id}/security
  controller: App\Controller\Profil\ProfilController::security
  methods: [GET|POST]

