home:
  path: /
  controller: App\Controller\HomeController::index

# Blog
blog.index:
  path: /blog
  controller: App\Controller\BlogController::index

blog.show:
  path: /blog/{slug}-{id}
  controller: App\Controller\BlogController::show
  requirements:
    slug:  '[a-z0-9\-]*'

blog.category:
  path: /blog/category/{slug}
  controller: App\Controller\BlogController::categoryIndex
  requirements:
    slug: '[a-z\-]*'

blog.like:
  path: /blog/{slug}-{id}/like
  controller: App\Controller\BlogController::like
  requirements:
    slug:  '[a-z0-9\-]*'
  methods: [GET]


# Administration
admin.home:
  path: /dashboard
  controller: App\Controller\Dashboard\DashboardController::dashboard

# Manage Blog
admin.blog:
  path: /dashboard/blog
  controller: App\Controller\Dashboard\Blog\BlogController::index

admin.blog.manage.post:
  path: /dashboard/blog/manage/post
  controller: App\Controller\Dashboard\Blog\BlogController::managePost

admin.blog.post.create:
  path: /dashboard/blog/manage/post/create
  controller: App\Controller\Dashboard\Blog\BlogController::create
  methods: [GET|POST]

admin.blog.post.edit:
  path: /dashboard/blog/manage/post/edit/{id}
  controller: App\Controller\Dashboard\Blog\BlogController::edit
  methods: [GET|POST]

admin.blog.post.delete:
  path: /dashboard/blog/manage/post/{id}
  controller: App\Controller\Dashboard\Blog\BlogController::delete
  methods: [DELETE]

admin.blog.manage.categories:
  path: /dashboard/blog/manage/categories
  controller: App\Controller\Dashboard\Blog\BlogCategoriesController::index

admin.blog.categories.create:
  path: /dashboard/blog/manage/categories/create
  controller: App\Controller\Dashboard\Blog\BlogCategoriesController::create
  methods: [GET|POST]

admin.blog.categories.edit:
  path: /dashboard/blog/manage/categories/edit/{id}
  controller: App\Controller\Dashboard\Blog\BlogCategoriesController::edit
  methods: [GET|POST]

admin.blog.categories.delete:
  path: /dashboard/blog/manage/categories/{id}
  controller: App\Controller\Dashboard\Blog\BlogCategoriesController::delete
  methods: [DELETE]

admin.blog.manage.comment:
  path: /dashboard/blog/manage/comments
  controller: App\Controller\Dashboard\Blog\BlogCommentsController::comments
  methods: [GET|POST]

admin.blog.comment.edit:
  path: /dashboard/blog/manage/comments/edit/{id}
  controller: App\Controller\Dashboard\Blog\BlogCommentsController::edit
  methods: [GET|POST]

admin.blog.comment.delete:
  path: /dashboard/blog/manage/comments/{id}
  controller: App\Controller\Dashboard\Blog\BlogCommentsController::delete
  methods: [DELETE]

# Manage users
admin.users:
  path: /dashboard/users
  controller: App\Controller\Dashboard\Users\UsersController::index

admin.user.create:
  path: /dashboard/users/create
  controller: App\Controller\Dashboard\Users\UsersController::create
  methods: [GET|POST]

admin.user.edit:
  path: /dashboard/users/edit/{id}
  controller: App\Controller\Dashboard\Users\UsersController::edit
  methods: [GET|POST]

admin.user.delete:
  path: /dashboard/users/{id}
  controller: App\Controller\Dashboard\Users\UsersController::delete
  methods: [DELETE]

# Security
login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET|POST]

logout:
  path: /logout

register:
  path: /register
  controller: App\Controller\SecurityController::register
  methods: [GET|POST]

confirmation_account:
  path: /confirm-account/{token}-{id}
  controller: App\Controller\SecurityController::confirmAccount
  methods : [GET]

forgot_password_request:
  path: /forgot-password
  controller: App\Controller\SecurityController::forgotPasswordRequest
  methods: [GET|POST]

change_password_post:
  path: /forgot-password/{token}
  controller: App\Controller\SecurityController::forgotPasswordPost
  methods: [GET|POST]

github_connect:
  path: /auth/github
  controller: App\Controller\Auth\GithubAuthController::connect

google_connect:
  path: /auth/google
  controller: App\Controller\Auth\GoogleAuthController::connect

twitch_connect:
  path: /auth/twitch
  controller: App\Controller\Auth\TwitchAuthController::connect