home:
  path: /
  controller: App\Controller\HomeController::index

blog.index:
  path: /blog
  controller: App\Controller\BlogController::index

blog.show:
  path: /blog/{slug}-{id}
  controller: App\Controller\BlogController::show
  requirements:
    slug:  '[a-z0-9\-]*'

blog.category:
  path: /blog/category/{slug}
  controller: App\Controller\BlogController::categoryIndex
  requirements:
    slug: '[a-z\-]*'

# Administration
admin.home:
  path: /dashboard
  controller: App\Controller\Dashboard\DashboardController::dashboard

# Manage Blog

admin.blog:
  path: /dashboard/blog
  controller: App\Controller\Dashboard\DashboardBlogController::index

admin.blog.manage.post:
  path: /dashboard/blog/manage/post
  controller: App\Controller\Dashboard\DashboardManageBlogPost::index

admin.blog.post.create:
  path: /dashboard/blog/manage/post/create
  controller: App\Controller\Dashboard\DashboardManageBlogPost::create
  methods: [GET|POST]

admin.blog.post.edit:
  path: /dashboard/blog/manage/post/edit/{id}
  controller: App\Controller\Dashboard\DashboardManageBlogPost::edit
  methods: [GET|POST]

admin.blog.post.delete:
  path: /dashboard/blog/manage/post/{id}
  controller: App\Controller\Dashboard\DashboardManageBlogPost::delete
  methods: [DELETE]

admin.blog.manage.categories:
  path: /dashboard/blog/manage/categories
  controller: App\Controller\Dashboard\DashboardBlogCategoriesController::index

admin.blog.categories.create:
  path: /dashboard/blog/manage/categories/create
  controller: App\Controller\Dashboard\DashboardBlogCategoriesController::create

admin.blog.categories.edit:
  path: /dashboard/blog/manage/categories/edit/{id}
  controller: App\Controller\Dashboard\DashboardBlogCategoriesController::edit

admin.blog.categories.delete:
  path: /dashboard/blog/manage/categories/{id}
  controller: App\Controller\Dashboard\DashboardBlogCategoriesController::delete


# Manage users
admin.users:
  path: /dashboard/users
  controller: App\Controller\Dashboard\DashboardUsersController::index

admin.user.create:
  path: /dashboard/users/create
  controller: App\Controller\Dashboard\DashboardUsersController::create
  methods: [GET|POST]

admin.user.edit:
  path: /dashboard/users/edit/{id}
  controller: App\Controller\Dashboard\DashboardUsersController::edit
  methods: [GET|POST]

admin.user.delete:
  path: /dashboard/users/{id}
  controller: App\Controller\Dashboard\DashboardUsersController::delete
  methods: [DELETE]

# Login
login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET|POST]

logout:
  path: /logout

register:
  path: /register
  controller: App\Controller\SecurityController::register
  methods: [GET|POST]