name: Mael Workflows Build and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: PHPUnit test
    runs-on: [ubuntu-latest]
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.3', '7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@1.7.0
        with:
          php-version: ${{ matrix.php }}
      - name: Install Composer and Dependencies
        uses: php-actions/composer@v1
        with:
          command: composer update --no-interaction --prefer-dist --no-suggest
      - name: PHPUnit tests
        uses: php-actions/phpunit@v1
        with:
          config: phpunit.xml.dist
          bootstrap: tests/bootstrap.php